language: csharp
mono: none
dotnet: 2.2.101
branches:
  only:
  - master
  - /release-.*/
  - /^\d+\.\d+\.\d+(-\S*)?$/
script: "./build.sh"
git:
  depth: false
matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx